### ISSUE TITLE
No Support for C# WinForms / Console Applications?

### ISSUE THREAD

**Issue by DefaultO** [gigajew/WinXRunPE-x86_x64#8]
## So I am using this piece of art for one of my Rythm Game Bots.
I was looking for something like this pretty long now. Accidentally stumped upon this Git.

This works perfectly fine with the **puppy64.exe** that was given already. Tried to implement it into the Cheat then by adding it on a Button Click Event. No problems while doing it. But when I tried debugging it, this ugly Error Message appeared telling me that it can't hijack the **calc.exe** with my **bot.exe**. (leading to a Microsoft Page telling me that my .NET Framework is broken, etc.)

![Alt Text](https://i.imgur.com/XlR51So.png)

I tried it with an empty **C# WinForm** afterward. Same issue. I tried it with a **C# Console Application**. Nothing happens. Are there other things that I need to do besides using two x64 Applications? Could it be the fault of **.NET Framework 4.8**? Is it only for **C++ Applications**?

Looking forward to a reply! Cheers, mate.
###### - 0xD3F, 5. November 2019 - 22:12

**Comment by gigajew** [comment]
I don't think you can inject a .NET assembly into a native app like calc.exe using a traditional RunPE. However there is another solution for you, but it requires you inject a bootstrapper DLL into the native process and call a function load a .NET assembly into any process, I covered this here: https://hackforums.net/showthread.php?tid=6005424 but I don't provide the DLL injection method

**Comment by DefaultO** [comment]
Aight. Thank you @gigajew . I thought so.
